const PossibleWords=new Set("abruptly;absurd;abyss;affix;askew;avenue;awkward;axiom;azure;bagpipes;bandwagon;banjo;bayou;beekeeper;blitz;blizzard;boggle;bookworm;boxcar;boxful;buckaroo;buffalo;buffoon;buxom;buzzard;buzzing;buzzwords;caliph;cobweb;cockiness;croquet;crypt;curacao;cycle;daiquiri;dirndl;disavow;dizzying;duplex;dwarves;embezzle;equip;espionage;euouae;exodus;faking;fishhook;fixable;fjord;flapjack;flopping;fluffiness;flyby;foxglove;frazzled;frizzled;fuchsia;funny;gabby;galaxy;galvanize;gazebo;giaour;gizmo;glowworm;glyph;gnarly;gnostic;gossip;grogginess;haiku;haphazard;hyphen;iatrogenic;icebox;injury;ivory;ivy;jackpot;jaundice;jawbreaker;jaywalk;jazziest;jazzy;jelly;jigsaw;jinx;jiujitsu;jockey;jogging;joking;jovial;joyful;juicy;jukebox;jumbo;kayak;kazoo;keyhole;khaki;kilobyte;kiosk;kitsch;kiwifruit;klutz;knapsack;larynx;lengths;lucky;luxury;lymph;marquis;matrix;megahertz;microwave;mnemonic;mystify;naphtha;nightclub;nowadays;numbskull;nymph;onyx;ovary;oxidize;oxygen;pajama;peekaboo;phlegm;pixel;pizazz;pneumonia;polka;pshaw;psyche;puppy;puzzling;quartz;queue;quips;quixotic;quiz;quizzes;quorum;razzmatazz;rhubarb;rhythm;rickshaw;schnapps;scratch;shiv;snazzy;sphinx;spritz;squawk;staff;strength;strengths;stretch ;stronghold;stymied;subway;swivel;syndrome;thriftless;thumbscrew;topaz;transcript;transgress;transplant;triphthong;twelfth;twelfths;unknown;unworthy;unzip;uptown;vaporize;vixen;vodka;voodoo;vortex;voyeurism;walkway;waltz;wave;wavy;waxy;wellspring;wheezy;whiskey;whizzing;whomever;wimpy;witchcraft;wizard;woozy;wristwatch;wyvern;xylophone;yachtsman;yippee;yoked;youthful;yummy;zephyr;zigzag;zigzagging;zilch;zipper;zodiac;zombie;jazz;quaff;zinc;oak;vex;vox;foxing;foxed;queued;fuzzy;quay;pinup;fox;yuk;vaquero;jazzier;quizzed;hazing;favour;yoking;quays;quark;joked;guyed;foyer;bumph;huge;quip;gibe;rump;guan;oaks;murk;fezzes;yuck;keno".split(";")),
REGEX_SPACE=/[^ ]/g;let gameSettingShowWordText=null;
const configType={CONF_WORD:"conf_word",CONF_PLAYERLIST:"conf_playerlist",CONF_PLAYERQUEUE:"conf_playerqueue"},config={current:null,data:{},set(a,b){return this.current?(this.data[this.current]=this.data[this.current]||{},this.data[this.current][a]=b,!0):!1},remove(a){return this.current&&this.data[this.current]&&this.data[this.current][a]?(delete this.data[this.current][a],0===Object.keys(this.data[this.current]).length&&delete this.data[this.current],!0):!1},get(a,b){return this.current&&this.data[this.current]&&
void 0!==this.data[this.current][a]?this.data[this.current][a]:b},save(){this.current&&window.localStorage.setItem("config",JSON.stringify(this.data))},load(){this.current="CONF_GAME_TWITCHHANGMAN";const a=window.localStorage.getItem("config");this.data=a?JSON.parse(a):{};this.data[this.current]||(this.data[this.current]={})}};window.configType=configType;window.config=config;window.config.load();
var isOnIOS=navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPhone/i),eventName=isOnIOS?"pagehide":"beforeunload";window.addEventListener(eventName,function(){window.config.save()});
window.setting={getKeyName(a){return"setting_"+a},registerSetting(a,b,c){let d=document.querySelector("#"+a);if(d){d.configKeyName=this.getKeyName(a);switch(d.type){case "checkbox":case "radio":d.valueProperty="checked";d.eventName="input";break;default:d.valueProperty="value",d.eventName="input"}d[d.valueProperty]=window.config.get(d.configKeyName,b);d.addEventListener(d.eventName,function(e){window.config.set(e.target.configKeyName,e.target[e.target.valueProperty]);c&&c(e)})}}};
class Logger{constructor(a="new logger",b="00FFC5",c=null,d="font-family: sans-serif; font-size: 15px;"){this.prefix=a;this.prefixColor=b;this.logIcon=c;this.logStyle=d}log(a,b="ffffff"){this.logIcon?console.log(`%c   %c[${this.prefix}] %c${a}`,`font-size: 16px; background-image: url("${this.logIcon}"); background-repeat: no-repeat; background-position: center;`,`font-weight: bold; color: #${this.prefixColor}; ${this.logStyle}`,`font-weight: normal; color: #${b}; ${this.logStyle}`):console.log(`%c[${this.prefix}] %c${a}`,
`font-weight: bold; color: #${this.prefixColor}; ${this.logStyle}`,`font-weight: normal; color: #${b}; ${this.logStyle}`)}}const TMIConfig={CHANNEL_NAME:"",OAUTH_TOKEN:"",COMMAND_PREFIX:"-",COMMAND_SEPARATOR:" ",HANGMAN_NAME:"td",SYSTEM_CHAT_USER:{name:"\ud835\udce3\ud835\udcd3",color:"#ff0000",unsafe:!0}};let socket=null;
function tmiStartWebSocket(a=null){TMIConfig.CHANNEL_NAME=window.config.get(window.setting.getKeyName("setting-tmi-channelname"));TMIConfig.OAUTH_TOKEN=window.config.get(window.setting.getKeyName("setting-tmi-oauth"));if(!TMIConfig.CHANNEL_NAME||!TMIConfig.OAUTH_TOKEN)return!1;socket=new WebSocket("wss://irc-ws.chat.twitch.tv:443");socket.onopen=function(){a&&a();tmiWebSocketSuccess=!0;TMILogger.log("connected");socket.send(`PASS ${TMIConfig.OAUTH_TOKEN}`);socket.send(`NICK ${TMIConfig.CHANNEL_NAME}`);
socket.send(`JOIN #${TMIConfig.CHANNEL_NAME}`)};socket.onmessage=function(b){if(b.data.startsWith("PING"))socket.send("PONG :tmi.twitch.tv");else if(b=tmiParseMessage(b.data)){const {username:c,content:d}=b;if(d.startsWith(TMIConfig.COMMAND_PREFIX+TMIConfig.HANGMAN_NAME+TMIConfig.COMMAND_SEPARATOR))switch(b=d.toLowerCase().trim().slice(TMIConfig.COMMAND_PREFIX.length+TMIConfig.HANGMAN_NAME.length+TMIConfig.COMMAND_SEPARATOR.length).split(TMIConfig.COMMAND_SEPARATOR),b[0]){case "join":game.addUserToAcceptanceQueue(c);
break;case "leave":game.kickUser(c);break;case "guess":game.guess(c,b[1]);break;case "admin":if("whimsicalweasel52"===c)switch(b[1]){case "weaselbox":showWeaselBoxWindow.Show()}}else(b=game.getPlayerByName(c))&&game.newMessage({name:c,color:b.color,unsafe:!1},d)}};socket.onerror=function(b){TMILogger.log("ws error:",b)};socket.onclose=function(){TMILogger.log("disconnected");alert("Lost connected to Twitch IRC")};return!0}tmiStartWebSocket();
let tmiRestartWebSocketWindowAnimTimeout=-1,tmiWebSocketSuccess=!1;function handleWebSocketRestart(a){PopupModal.show("WEBSOCKET STATUS",a);(tmiWebSocketSuccess=tmiStartWebSocket(function(){tmiRestartWebSocketWindowAnimTimeout=setTimeout(function(){PopupModal.hide();gameSettingModal.modal("show")},500)}))||PopupModal.show("WEBSOCKET STATUS","Failed to connect to WebSocket")}
function tmiRestartWebSocket(){if(socket)switch(socket.readyState){case WebSocket.OPEN:socket.onclose=function(){TMILogger.log("restarting ws")};socket.close();handleWebSocketRestart("Restarting...");break;case WebSocket.CLOSED:socket.onclose=null,handleWebSocketRestart("Starting...")}else handleWebSocketRestart("Starting...")}function tmiRestartWebSocketButton(){gameSettingModal.modal("hide");tmiRestartWebSocket()}const TMILogger=new Logger("ircmanager","00FFC5");window.tmiSendMessage=function(a){socket.send(`PRIVMSG #${TMIConfig.CHANNEL_NAME} :${a}`)};
function tmiParseMessage(a){var b=a.split(" ");switch(b[1]){case "PRIVMSG":return a=b[0].split("!")[0].substring(1),b=b.slice(3).join(" ").substring(1),{username:a,content:b};case "NOTICE":PopupModal.show("TMI NOTICE",b.slice(3).join(" ").substring(1)),socket.onclose=null,clearTimeout(tmiRestartWebSocketWindowAnimTimeout),tmiWebSocketSuccess=!1}return null}window.addEventListener("unload",function(){TMILogger.log("try to disconnect");socket&&socket.readyState===WebSocket.OPEN&&socket.close()});
class Player{hashStringToColor(a){let b=0;for(let c=0;c<a.length;c++)b=a.charCodeAt(c)+((b<<5)-b),b&=b;a=b;return`rgb(${(a&16711680)>>16}, ${(a&65280)>>8}, ${a&255})`}constructor(a){this.name=a;this.color=this.hashStringToColor(a)}}Player.prototype.toString=function(){return this.name};
class HangmanGame{constructor(a){this.lastWord=this.word=null;this.maxGuesses=a;HangmanGame.players=window.config.get(configType.CONF_PLAYERLIST,[]).map(b=>new Player(b.name));this.guessedLetters=[];this.guessedLettersOrdered=[];this.currentPlayerIndex=this.incorrectGuesses=0;this.finished=this.started=!1;this.logger=new Logger("hangman","D55672");HangmanGame.playerMessages=[];HangmanGame.playersJoinQueue=window.config.get(configType.CONF_PLAYERQUEUE,[]);this.lettersFromPlayers=[];this.winConditionRegex=
/[^a-zA-Z]/g;this.reset(!0)}reset(a){this.wordLength=(this.word=window.config.get(configType.CONF_WORD,null))?this.word.length:0;this.word&&(this.lastWord=this.word);this.guessedLetters=[];this.guessedLettersOrdered=[];this.currentPlayerIndex=this.incorrectGuesses=0;this.finished=this.started=!1;this.lettersFromPlayers=[];window.setting&&window.config&&(window.config.get(window.setting.getKeyName("setting-clear-messages"),!0)?(HangmanGame.playerMessages=[],this.clearMessages()):HangmanGame.playerMessages.forEach(b=>
{b.rendered=!1}),!a&&window.config.get(window.setting.getKeyName("setting-shuffle-players"),!0)&&this.shufflePlayers())}randomWord(){let a;const b=this.word||this.lastWord;do a=PossibleWords.random();while(a===b);this.setWord(a)}start(){if(0===HangmanGame.players.length)return this.logger.log("No players cant start game"),!1;let a=this;GameSlashAnimation.show("GAME","START!!!",function(){a.currentPlayerIndex=0;a.renderCurrentPlayer();game.newMessage(TMIConfig.SYSTEM_CHAT_USER,"New Game Started!");
GameSlashAnimation.show("FIRST UP...",HangmanGame.players[a.currentPlayerIndex].name,function(){a.finished=!1;a.started=!0})});return!0}draw(){this.main=document.querySelector("#hangman-main");this.container=document.querySelector("#hangman-container");this.playerNameDiv=document.querySelector("#player-name");this.playerChatList=document.querySelector("#player-chat-list");this.row=document.querySelector("#hangman-row");this.row.innerHTML="";this.nonanswers=document.querySelector("#hangman-nonanswers");
this.nonanswers.innerHTML="";this.keyElementMap={};"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").forEach(a=>{let b=document.createElement("div");b.classList="letter";b.innerText=a;this.keyElementMap[a]=b;this.nonanswers.appendChild(b)});this.gallowStage=document.querySelector("#hangman-gallow-goob-stage");this.gallowStage.src="assets/goob_stages/0.png";this.renderBoard();this.fadeInBoard();this.playerNameDiv.textContent="THE GAME HAS NOT BEEN STARTED"}end(){this.finished=!0;this.started=!1}guess(a,b){if(!GameSlashAnimation.active){if(!this.started||
this.finished)return!1;var c=this.getPlayerByName(a);if(!c||c!==HangmanGame.players[this.currentPlayerIndex])return!1;b=b.toUpperCase();if(this.lettersFromPlayers.some(d=>d.letter===b))return game.newMessage(TMIConfig.SYSTEM_CHAT_USER,`@${c.name} Someone already guessed this letter. Try again.`),!1;this.lettersFromPlayers.push({playerName:a,letter:b});1<b.length?b!==this.word?(this.incorrectGuess(b),this.incorrectGuesses>=this.maxGuesses?this.finish(null):this.nextPlayer()):(this.guessedLettersOrdered=
b.split(""),this.finish(c,!0)):1===b.length&&(this.word.includes(b)?(this.guessedLetters.push({flashed:!1,letter:b}),this.correctGuess(b)):this.incorrectGuess(b),game.newMessage(TMIConfig.SYSTEM_CHAT_USER,`@${c.name} guessed "${b}"!`),this.renderBoard(),this.checkWin()?this.finish(c):this.incorrectGuesses>=this.maxGuesses?this.finish(null):this.nextPlayer());return!0}}getPlayerByName(a){return HangmanGame.players.find(b=>b.name===a)||null}checkWin(){return this.word.replace(this.winConditionRegex,
"")===this.guessedLettersOrdered.join("")}fadeInBoard(){document.body&&(document.body.style.display="block",document.body.style.opacity=0,setTimeout(()=>{document.body.style.transition="opacity 1s";document.body.style.opacity=1},0))}incorrectGuess(a){this.incorrectGuesses++;this.gallowStage.src=`assets/goob_stages/${this.incorrectGuesses}.png`;1===a.length&&this.keyElementMap[a]&&this.keyElementMap[a].classList.add("crossed")}correctGuess(a){1===a.length&&this.keyElementMap[a]&&this.keyElementMap[a].classList.add("green")}renderBoard(a=
!1,b=!1){if(this.row){this.row.innerHTML="";var c=0;this.word.split(" ").forEach((d,e)=>{let k=document.createElement("div");k.classList="word";d.split("").forEach((f,n)=>{let g=document.createElement("div");g.classList="hangman-letter";let h=document.createElement("span");if(f.match(this.winConditionRegex))h.textContent=f;else{let l=this.guessedLetters.find(p=>p.letter===f),m=this.guessedLetters.indexOf(l);a||-1!==m?((b||0<this.guessedLetters.length&&m===this.guessedLetters.length-1&&!this.guessedLetters[m].flashed)&&
g.animate([{color:"#05ff31",borderColor:"#05ff31"},{color:"#ffffff",borderColor:"#ffffff"}],{duration:1E3}),h.textContent=f,l&&(l.flashed=!0),this.guessedLettersOrdered[n+c]=f):h.textContent=""}g.appendChild(h);k.appendChild(g)});c+=d.length;this.row.appendChild(k)})}}finish(a,b=!1){this.finished=!0;let c=`<span class="d-block mt-3">The word was <b style="color: #3586ff !important;text-shadow: 0 0 #0d6efd;">${this.lastWord}</b>!</span>`;a?(this.logger.log(`winner is ${a.name}!`),game.newMessage(TMIConfig.SYSTEM_CHAT_USER,
`@${a.name} guessed the word! The word was "${this.lastWord}"!`),PopupModal.show("WINNER!",`<p><b style="color: ${a.color}">${a.name}</b> guessed the word!</p>${emote.img_text(emoteType.ailuYay).repeat(3)}`+c)):(this.logger.log("nobody won"),game.newMessage(TMIConfig.SYSTEM_CHAT_USER,`Nobody won this game. The word was "${this.lastWord}"!`),PopupModal.show("NO WINNER!",`<p>Nobody won this game. Put your all into it next time!</p>${emote.img_text(emoteType.ailuBonk)}${emote.img_text(emoteType.ailuBork)}${emote.img_text(emoteType.ailuVeryAngry)}`+
c));this.renderBoard(!0,b);this.setWord(null);return!0}setWord(a){if(a){this.word=a.toUpperCase();try{game.newMessage(TMIConfig.SYSTEM_CHAT_USER,`Got a new word! ${"*".repeat(a.length)}`)}catch{}this.wordLength=this.word.length;this.lastWord=this.word;gameSettingShowWordText&&(gameSettingShowWordText.textContent=gameSettingShowWordText.state?a.toUpperCase():a.replace(REGEX_SPACE,"*"));this.renderBoard()}else this.word=null;window.config.set(configType.CONF_WORD,this.word)}shufflePlayers(){HangmanGame.players.shuffle();
game.newMessage(TMIConfig.SYSTEM_CHAT_USER,"Shuffled Players");this.renderPlayerListModal()}addUserToAcceptanceQueue(a){HangmanGame.playersJoinQueue.includes(a)||HangmanGame.players.some(b=>b.name===a)||(HangmanGame.playersJoinQueue.push(a),this.renderPlayerListModal())}ignoreUserToAcceptanceQueue(a){HangmanGame.playersJoinQueue.includes(a)&&(HangmanGame.playersJoinQueue=HangmanGame.playersJoinQueue.filter(b=>b!==a),this.renderPlayerListModal())}ignoreAllToAcceptanceQueue(){HangmanGame.playersJoinQueue=
[];this.renderPlayerListModal()}registerUser(a){if(!this.started&&!this.finished){if(HangmanGame.players.some(b=>b.name===a))this.logger.log(`Player ${a} already registered`);else{HangmanGame.playersJoinQueue=HangmanGame.playersJoinQueue.filter(c=>c!==a);let b=new Player(a);HangmanGame.players.push(b);this.logger.log(`Player ${b.name} joined the game`)}this.renderPlayerListModal()}}registerAll(){this.started||this.finished||(HangmanGame.playersJoinQueue.forEach(a=>{a=new Player(a);HangmanGame.players.push(a)}),
HangmanGame.playersJoinQueue=[],this.renderPlayerListModal())}kickUser(a){const b=HangmanGame.players.findIndex(c=>c.name===a);-1!==b?(HangmanGame.players.splice(b,1),b===this.currentPlayerIndex&&this.nextPlayer(),this.currentPlayerIndex>=HangmanGame.players.length&&(this.currentPlayerIndex=0),this.renderPlayerListModal()):this.ignoreUserToAcceptanceQueue(a);0===HangmanGame.players.length&&this.end()}kickAll(){HangmanGame.players=[];this.renderPlayerListModal()}nextPlayer(){this.currentPlayerIndex++;
this.currentPlayerIndex>=HangmanGame.players.length&&(this.currentPlayerIndex=0);if(this.started&&!this.finished&&0<HangmanGame.players.length){let a=this;GameSlashAnimation.show("NEXT UP...",HangmanGame.players[this.currentPlayerIndex].name,function(){a.renderCurrentPlayer()})}}renderPlayerListModal(){window.config.set(configType.CONF_PLAYERQUEUE,HangmanGame.playersJoinQueue);window.config.set(configType.CONF_PLAYERLIST,HangmanGame.players);addPlayersModal&&addPlayersModal.hasClass("show")&&addPlayersModalRender()}renderCurrentPlayer(){if(this.playerNameDiv){let a=
HangmanGame.players[this.currentPlayerIndex];a&&(this.playerNameDiv.innerHTML=`ACTIVE PLAYER: <span style="color: ${a.color}">${a.name.escapeHTML()}</span>`)}}clearMessages(){this.playerChatList&&(this.playerChatList.innerHTML="")}newMessage(a,b){HangmanGame.playerMessages.push({sender:a,content:b});a===TMIConfig.SYSTEM_CHAT_USER&&window.tmiSendMessage&&window.tmiSendMessage("[\ud835\udce3\ud835\udcd3]: "+b);game.renderMessages()}renderMessages(){HangmanGame.playerMessages.forEach(a=>{if(!a.rendered){let c=
document.createElement("div");c.classList.add("message");var b=document.createElement("span");b.classList.add("name");b.textContent=a.sender.name;c.appendChild(b);a.sender.color&&(b.style.color=a.sender.color);b=document.createElement("span");b.classList.add("text");b[a.sender.unsafe?"innerHTML":"textContent"]=": "+a.content;c.appendChild(b);this.playerChatList.appendChild(c);a.rendered=!0}});this.playerChatList.scrollTop=this.playerChatList.scrollHeight}}HangmanGame.players=null;
HangmanGame.playerMessages=null;HangmanGame.playersJoinQueue=null;String.prototype.escapeHTML=function(){return this.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};Array.prototype.remove=function(){for(var a=arguments,b=a.length,c;b&&this.length;)for(c=this.indexOf(a[--b]);-1!==c;)this.splice(c,1),c=this.indexOf(a[b]);return this};
Array.prototype.shuffle=function(){let a=this.length;for(;0!=a;){let b=Math.floor(Math.random()*a);a--;[this[a],this[b]]=[this[b],this[a]]}return this};Set.prototype.random=function(){const a=Array.from(this);return a[Math.floor(Math.random()*a.length)]};Node.prototype.appendChildren=function(){let a=[...arguments];1==a.length&&Array.isArray(a[0])&&(a=a[0]);const b=document.createDocumentFragment();a.forEach(c=>b.appendChild(c));this.appendChild(b)};
Array.prototype.invoke=function(){this.forEach((a,b)=>{"function"===typeof a&&a(b)})};const game=new HangmanGame(7),PopupModal={element:window.$("#bs-popup-modal"),init(){this.title=this.element[0].querySelector(".modal-title");this.body=this.element[0].querySelector(".modal-body")},show(a,b){this.element.modal("show");this.title.innerHTML=a;this.body.innerHTML="string"===typeof b?b:"";"string"!==typeof b&&this.body.appendChild(b)},hide(){this.element.modal("hide")}};PopupModal.init();
const emoteType={ailuYay:"ailuYay.png",ailuBonk:"ailuBonk.png",ailuVeryAngry:"ailuVeryAngry.gif",ailuBork:"ailuBork.gif"},emote={path:"assets/e/",createImgElement(a){let b=document.createElement("img");b.src=this.path+a;return b},img_text(a){return`<img src="${this.path+a}"/>`}},GameKeyboardDisplayer={keys:"ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),letterToElementDict:{},left:document.querySelector("div#keyboard-display-left"),right:document.querySelector("div#keyboard-display-right"),render(){this.left.innerHTML=
"";this.right.innerHTML="";const a=Math.ceil(this.keys.length/2),b=c=>{const d=document.createElement("div");d.className="keyboard-display-key";d.textContent=c;d.currentId=3;return this.letterToElementDict[c]=d};this.keys.slice(0,a).forEach(c=>this.left.appendChild(b(c)));this.keys.slice(a).forEach(c=>this.right.appendChild(b(c)))},changeColor(a,b){a=this.letterToElementDict[a.toUpperCase()];a.currentId<b||(a.currentId=b,a.className=`keyboard-display-key ${["correct","present","absent"][b]}`)}},GameSlashAnimation=
{active:!1,tslash:document.querySelector("div#anim-display-tslash"),tlashTop:document.querySelector("div#anim-display-tslash-anim-top"),tlashAilu:document.querySelector("div#anim-display-tslash-anim-ailu"),show(a,b,c){GameSlashAnimation.active||(GameSlashAnimation.active=!0,GameSlashAnimation.tlashTop.innerHTML=a,GameSlashAnimation.tlashAilu.innerHTML=b,GameSlashAnimation.tslash.classList.add("show"),setTimeout(function(){GameSlashAnimation.tslash.classList.add("animation");setTimeout(function(){GameSlashAnimation.tslash.classList.remove("animation");
setTimeout(function(){GameSlashAnimation.tslash.classList.remove("show");GameSlashAnimation.active=!1;c&&c()},150)},1750)},150))}};function resetCommand(a=!1){game.reset(a);game.word||game.randomWord();game.draw()}resetCommand(!0);let startGame=document.querySelector("button#game-start"),endGame=document.querySelector("button#game-end");startGame.disabled=!1;
startGame.addEventListener("click",function(){game.started||game.finished||(tmiWebSocketSuccess?game.start()?(startGame.disabled=!0,endGame.disabled=!1,gameSettingRerollWord.disabled=!0,gameSettingRestartWebSocket.disabled=!0):PopupModal.show("Error","You cannot start the game with 0 players!"):PopupModal.show("Error","Please connect to Twitch TMI before starting the game."))});
endGame.addEventListener("click",function(){game.finished?(resetCommand(),startGame.disabled=!1,endGame.disabled=!0,gameSettingRerollWord.disabled=!1,gameSettingRestartWebSocket.disabled=!1):game.started&&game.finish(null)});let addPlayers=document.querySelector("button#game-players"),addPlayersModal=window.$("#bs-player-modal"),addPlayersModalBodyCurrent=addPlayersModal[0].querySelector(".modal-body-content-current"),addPlayersModalBodyPending=addPlayersModal[0].querySelector(".modal-body-content-pending");
addPlayers.addEventListener("click",function(){addPlayersModal.modal("show");addPlayersModalRender()});
function createPlayerElement(a,b,c){let d=document.createElement("div");d.classList.add("player");var e=document.createElement("span");e.style.color=b;e.textContent=a;d.appendChild(e);b=document.createElement("div");b.classList.add("player-controls");e=document.createElement("button");e.classList.add("btn",c?"btn-danger":"btn-success");e.textContent=c?"Kick":"Accept";e.addEventListener("click",function(){c?game.kickUser(a):game.registerUser(a)});b.appendChild(e);c||(e=document.createElement("button"),
e.classList.add("btn","btn-danger"),e.textContent="Reject",e.addEventListener("click",function(){game.ignoreUserToAcceptanceQueue(a)}),b.appendChild(e));d.appendChild(b);return d}
function addPlayersModalRender(){let a=addPlayersModalBodyCurrent.scrollTop,b=addPlayersModalBodyPending.scrollTop;addPlayersModalBodyCurrent.innerHTML="";addPlayersModalBodyPending.innerHTML="";HangmanGame.playersJoinQueue.forEach(c=>addPlayersModalBodyPending.appendChild(createPlayerElement(c,"#cccccc",!1)));HangmanGame.players.forEach(c=>addPlayersModalBodyCurrent.appendChild(createPlayerElement(c.name,c.color,!0)));addPlayersModalBodyCurrent.scrollTo(0,a);addPlayersModalBodyPending.scrollTo(0,
b)}let gameSetting=document.querySelector("button#game-setting"),gameSettingModal=window.$("#bs-setting-modal");gameSetting.addEventListener("click",function(){gameSettingModal.modal("show")});let gameSettingShowWord=document.querySelector("button#setting-show-word");gameSettingShowWordText=document.querySelector("span#setting-current-word");gameSettingShowWordText.state=!1;gameSettingShowWordText.textContent=game.word.replace(REGEX_SPACE,"*");
gameSettingShowWord.addEventListener("click",function(){gameSettingShowWordText.state=!gameSettingShowWordText.state;gameSettingShowWordText.textContent=gameSettingShowWordText.state?game.lastWord:game.word.replace(REGEX_SPACE,"*")});let gameSettingRerollWord=document.querySelector("button#setting-reroll-word");gameSettingRerollWord.disabled=!1;gameSettingRerollWord.addEventListener("click",function(){game.randomWord()});window.setting.registerSetting("setting-clear-messages",!0);
window.setting.registerSetting("setting-shuffle-players",!0);window.setting.registerSetting("setting-dgwapl",!1,function(a){game.dropWordsWithZeroCorrectLetters=a.target.checked});window.setting.registerSetting("setting-tmi-channelname","");window.setting.registerSetting("setting-tmi-oauth","");let gameSettingRestartWebSocket=document.querySelector("button#setting-tmi-restartwebsocket");gameSettingRestartWebSocket.addEventListener("click",tmiRestartWebSocketButton);let gamePlayersShuffle=document.querySelector("button#btn-players-shuffle");
gamePlayersShuffle.addEventListener("click",function(){game.shufflePlayers()});let gamePlayersKickAll=document.querySelector("button#btn-players-kickall");gamePlayersKickAll.addEventListener("click",function(){game.kickAll()});let gameQueueAcceptAll=document.querySelector("button#btn-queue-acceptall");gameQueueAcceptAll.addEventListener("click",function(){game.registerAll()});let gameQueueRejectAll=document.querySelector("button#btn-queue-rejectall");gameQueueRejectAll.addEventListener("click",function(){game.ignoreAllToAcceptanceQueue()});
function resizeWindow(){game.main&&(game.main.style.transform=`translateY(-50%) scale(${window.innerHeight/1018})`)};
